name: taskium
description: "Productivity app for task tracking, focus with Pomodoro sessions, and smarter time management."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.9
  firebase_core: ^3.14.0
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  riverpod: ^2.6.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/