name: taskium
description: "Productivity app for task tracking, focus with Pomodoro sessions, and smarter time management."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.9
  file_picker: ^10.2.0
  firebase_auth: ^5.6.1
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.9
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_pdfview: ^1.4.1+1
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  http: ^1.4.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  riverpod: ^2.6.1
  sqflite: ^2.4.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/